name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - hexo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        run:
          npm install -g hexo-cli
          npm install
          hexo generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.HEXO_DEPLOY }}
          publish_dir: ./public
          external_repository: XayahSuSuSu/XayahSuSuSu.github.io
          publish_branch: master
